version: '2'
services:

  consul:
    command: -server -bootstrap -ui-dir /ui
    image: progrium/consul
    networks: 
    - vaultnet 
    ports:
    - 8500:8500 # optional web ui

  vault:
    command: server -config=/config/vault_with_consul.hcl
    depends_on:
    - consul
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200' # not https for this demo
    image: vault
    cap_add:
    - IPC_LOCK
    networks: 
    - vaultnet
    ports:
    - 8200:8200
    volumes:
    - ./config:/config

  mssql:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Passw0rd'
    networks:
    - vaultnet
    ports:
    - 1433:1433

  # a bash shell with a few useful tools installed
  # first run: toolbox\build.ps1
  # use with: docker-compose run toolbox bash
  toolbox:
    image: toolbox
    environment:
      VAULT_HOST: 'vault'
    networks:
    - vaultnet
    volumes:
    - ./scripts:/scripts
    working_dir: /scripts

networks:
  vaultnet: